### ISSUE TITLE
Gut Data request

### ISSUE THREAD

**Issue by bensilke-amd** [bensilke-amd/biol3209#10]

**Comment by GavinHuttley** [comment]
UPDATE: We're working on this in the 8am Thursday morning HPO meeting.

**Comment by bensilke-amd** [comment]
is this in person or virtual? I'm happy to come in/ join the call.

**Comment by GavinHuttley** [comment]
both. Same as lab meeting room

**Comment by bensilke-amd** [comment]
Data provided so closing issue. issue is now the database population
