### ISSUE TITLE
Soil data collection

### ISSUE THREAD

**Issue by bensilke-amd** [bensilke-amd/biol3209#2]
Creating an issue to request the soil data sourced by gavin.

**Comment by GavinHuttley** [comment]
[Soil data](https://www.dropbox.com/s/bzgjdjozycy7tac/soil_reference_genomes.zip?dl=0) Just a collection of gzipped genbank formatted files.
[RefSoil](https://pubmed.ncbi.nlm.nih.gov/27935589/) paper.

**Comment by bensilke-amd** [comment]
Data sourced so closing issues

**Comment by bensilke-amd** [comment]
closed as data sourced
