### ISSUE TITLE
MetaGeneMark2 review

### ISSUE THREAD

**Issue by bensilke-amd** [bensilke-amd/biol3209#7]
pros/cons of this software

**Comment by bensilke-amd** [comment]
This program seems to do what the intention for mine was

**Comment by GavinHuttley** [comment]
We will want to see if prediction accuracy is affected by environment

**Comment by bensilke-amd** [comment]
https://github.com/karlgem/metagenemark-2

**Comment by biolinyu** [comment]
MetaGeneMark-2 paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6028130/

**Comment by KatherineCaley** [comment]
MetaGeneMark-2 preprint in biorxiv last month: https://www.biorxiv.org/content/10.1101/2022.07.25.500264v1

**Comment by bensilke-amd** [comment]
closed as reviewed
